---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: "testing"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-test-password
type: Opaque
stringData:
  password: "MyPassword1!"