#
# Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  {{- include "oracle-db-labels" . | indent 2 }}
  {{- if .Values.loadBalService }}
  annotations:
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
    oci.oraclecloud.com/load-balancer-type: nlb
  {{- end }}
spec:
{{- if .Values.loadBalService }}
  type: LoadBalancer
{{- else}}
  type: NodePort
{{- end }}
  ports:
  - name: {{ .Chart.Name }}
    protocol: TCP
    port: 1521
    targetPort: {{ .Chart.Name }}
  selector:
    app: {{ .Chart.Name }}
---
