apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: {{ .Values.replicaCount }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodb.adminName }}
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
    - name: {{ .Values.mongodb.mongotestName }}
      db: mongo_test
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-test-password
      roles:
        - name: dbOwner
          db: mongo_test
      scramCredentialsSecretName: mongotest-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: {{ .Values.mongodb.adminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-test-password
type: Opaque
stringData:
  password: {{ .Values.mongodb.mongotestPassword }}
