apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "student-api.labels" . | nindent 4 }}
data: {{- (.Files.Glob "config/*.yml").AsConfig | nindent 2 }}